name: Update WakaTime Stats

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update README with WakaTime stats
        uses: YouEclipse/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          UPDATE_OPTION: MARKDOWN
          MARKDOWN_FILE: README.md
          GIST_BARSTYLE: SOLIDLT
          GIST_BARLENGTH: 25
          GIST_TIMESTYLE: SHORT
